export const C = {
  //Rendering
  FRAME_INTERVAL: 1000 / 60,
  IDLE_FRAME_INTERVAL: 1000 / 8,
  VISIBLE_PRIORITY_COUNT: 6,
  //Camera
  DEFAULT_FOV: 75,
  NEAR: 0.1,
  FAR: 10,
  CAMERA_DISTANCE: 10,

  DEFAULT_WIDTH: 300,
  DEFAULT_HEIGHT: 200,
  INTERSECTION_THRESHOLD: 0.1,
  INTERSECTION_MARGIN: "150px",
  AUTO_ROTATE_SPEED: 2.0,
};
