export const SHIP = {
  MAX_SPEED: 0.5,
  ACCELERATION: 0.02,
  DECELERATION: 0.01,
  VERTICAL_MAX_SPEED: 0.4,
  VERTICAL_ACCELERATION: 0.02,
  VERTICAL_DECELERATION: 0.01,
  ROTATION_SPEED: 0.03,
  TILT_AMOUNT: 0.3,
  TILT_SPEED: 0.05,
  ORIENTATION_RESET_SPEED: 0.03,
};
